import type { PolicyTerm } from "@/features/policy/types";

export const defaultDictionaryId = "dict-brandguard-default";

export const mockPolicyTerms: PolicyTerm[] = [
  {
    brandId: "brand-northstar",
    category: "guarantee_claim",
    createdAt: "2026-07-01T09:00:00.000Z",
    enabled: true,
    id: "term-001",
    matchType: "contains",
    reason: "객관적 조건 없이 보장성 표현을 사용하는 것은 브랜드 정책상 제한됩니다.",
    replacementSuggestion: "조건 충족 시 제공",
    severity: "high",
    term: "무료 보장",
    type: "forbidden",
    updatedAt: "2026-07-01T09:00:00.000Z",
  },
  {
    brandId: "brand-northstar",
    category: "comparative_rank",
    createdAt: "2026-07-01T09:10:00.000Z",
    enabled: true,
    id: "term-002",
    matchType: "contains",
    reason: "근거가 명확하지 않은 순위 표현은 공개 전 검토가 필요합니다.",
    replacementSuggestion: "많은 고객이 선택한",
    severity: "medium",
    term: "업계 1위",
    type: "caution",
    updatedAt: "2026-07-01T09:10:00.000Z",
  },
  {
    brandId: "brand-northstar",
    category: "exaggerated_claim",
    createdAt: "2026-07-01T09:20:00.000Z",
    enabled: true,
    id: "term-003",
    matchType: "normalized",
    reason: "과장 표현은 소비자 오해 가능성이 있어 맥락 확인이 필요합니다.",
    replacementSuggestion: "사용 환경에 따라 체감할 수 있는",
    severity: "medium",
    term: "무조건 효과",
    type: "caution",
    updatedAt: "2026-07-01T09:20:00.000Z",
  },
  {
    brandId: "brand-northstar",
    category: "event_condition_missing",
    createdAt: "2026-07-01T09:30:00.000Z",
    enabled: true,
    id: "term-004",
    matchType: "contains",
    reason: "이벤트 혜택 문구에는 조건, 기간, 대상 안내가 함께 필요할 수 있습니다.",
    replacementSuggestion: "기간과 조건을 함께 명시",
    severity: "low",
    term: "전원 증정",
    type: "caution",
    updatedAt: "2026-07-01T09:30:00.000Z",
  },
  {
    brandId: "brand-northstar",
    category: "legal_review_required",
    createdAt: "2026-07-01T09:40:00.000Z",
    enabled: true,
    id: "term-005",
    matchType: "regex",
    reason: "단정적인 치료·개선 표현은 업종과 매체에 따라 법무 검토가 필요합니다.",
    replacementSuggestion: "도움이 될 수 있음",
    severity: "critical",
    term: "(완치|치료\\s*보장)",
    type: "forbidden",
    updatedAt: "2026-07-01T09:40:00.000Z",
  },
];
